export const GET_REQUEST="GET_REQUEST";
export const GET_SUCCESSFUL="GET_SUCCESSFUL";
export const GET_FAILURE="GET_FAILURE"


export const CREATE_REQUEST="CREATE_REQUEST";
export const CREATE_SUCCESSFUL="CREATE_SUCCESSFUL";
export const CREATE_FAILURE="CREATE_FAILURE"


export const DELETE_REQUEST="DELETE_REQUEST";
export const DELETE_SUCCESSFUL="DELETE_SUCCESSFUL";
export const DELETE_FAILURE="DELETE_FAILURE"


export const UPDATE_REQUEST="DELETE_REQUEST";
export const UPDATE_SUCCESSFUL="DELETE_SUCCESSFUL";
export const UPDATE_FAILURE="DELETE_FAILURE"



export const GETBYID_REQUEST="DELETE_REQUEST";
export const GETBYID_SUCCESSFUL="DELETE_SUCCESSFUL";
export const GETBYID_FAILURE="DELETE_FAILURE"