export const SIGNUP_REQUEST="SIGNUP_REQUEST";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAILURE="SIGNUP_FAILURE";


export  const LOGIN_REQUEST="LOGIN_REQUEST";

export const LOGIN_SUCCESS="LOGIN_SUCCESS";

export const LOGIN_FAILURE="LOGIN_FAILURE";



export  const LOGOUT_REQUEST="LOGOUT_REQUEST";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";

export const LOGOUT_FAILURE="LOGOUT_FAILURE";


export  const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE="USER_UPDATE_FAILURE";



export  const GOOGLE_AUTHENTICATION_REQUEST="GOOGLE_AUTHENTICATION_REQUEST";
export const GOOGLE_AUTHENTICATION_SUCCESS="GOOGLE_AUTHENTICATION_SUCCESS";
export const GOOGLE_AUTHENTICATION_FAILURE="GOOGLE_AUTHENTICATION_FAILURE";

